// Set object pointer
   mcs_E = 0;
   mcs_pt = 0;
   mcs_m = 0;
   mcs_eta = 0;
   mcs_phi = 0;
   mcs_status = 0;
   mcs_barcode = 0;
   mcs_pdgId = 0;
   mcs_charge = 0;
   mcs_vx_x = 0;
   mcs_vx_y = 0;
   mcs_vx_z = 0;

   tree2->SetBranchAddress("mcs_n", &mcs_n, &b_mcs_n);
   tree2->SetBranchAddress("mcs_E", &mcs_E, &b_mcs_E);
   tree2->SetBranchAddress("mcs_pt", &mcs_pt, &b_mcs_pt);
   tree2->SetBranchAddress("mcs_m", &mcs_m, &b_mcs_m);
   tree2->SetBranchAddress("mcs_eta", &mcs_eta, &b_mcs_eta);
   tree2->SetBranchAddress("mcs_phi", &mcs_phi, &b_mcs_phi);
   tree2->SetBranchAddress("mcs_status", &mcs_status, &b_mcs_status);
   tree2->SetBranchAddress("mcs_barcode", &mcs_barcode, &b_mcs_barcode);
   tree2->SetBranchAddress("mcs_pdgId", &mcs_pdgId, &b_mcs_pdgId);
   tree2->SetBranchAddress("mcs_charge", &mcs_charge, &b_mcs_charge);
   tree2->SetBranchAddress("mcs_vx_x", &mcs_vx_x, &b_mcs_vx_x);
   tree2->SetBranchAddress("mcs_vx_y", &mcs_vx_y, &b_mcs_vx_y);
   tree2->SetBranchAddress("mcs_vx_z", &mcs_vx_z, &b_mcs_vx_z);
   // Set object pointer
   VectorSignalsR = 0;
   VectorSignalsL = 0;
   VectorSignalsCherR = 0;
   VectorSignalsCherL = 0;
   VectorL = 0;
   VectorR = 0;
   VectorR_loop=0;
   VectorL_loop=0;
   tree2->SetBranchAddress("Energyem", &Energyem, &b_Energyem);
   tree2->SetBranchAddress("EnergyScin", &EnergyScin, &b_EnergyScin);
   tree2->SetBranchAddress("EnergyCher", &EnergyCher, &b_EnergyCher);
   tree2->SetBranchAddress("NofCherenkovDetected", &NofCherenkovDetected, &b_NofCherenkovDetected);
   tree2->SetBranchAddress("neutrinoleakage", &neutrinoleakage, &b_neutrinoleakage);
   tree2->SetBranchAddress("leakage", &leakage, &b_leakage);
   tree2->SetBranchAddress("EnergyTot", &EnergyTot, &b_EnergyTot);
   tree2->SetBranchAddress("PrimaryParticleEnergy", &PrimaryParticleEnergy, &b_PrimaryParticleEnergy);
   tree2->SetBranchAddress("PrimaryParticleName", PrimaryParticleName, &b_PrimaryParticleName);
   tree2->SetBranchAddress("VectorSignalsR", &VectorSignalsR, &b_VectorSignalsR);
   tree2->SetBranchAddress("VectorSignalsL", &VectorSignalsL, &b_VectorSignalsL);
   tree2->SetBranchAddress("VectorSignalsCherR", &VectorSignalsCherR, &b_VectorSignalsCherR);
   tree2->SetBranchAddress("VectorSignalsCherL", &VectorSignalsCherL, &b_VectorSignalsCherL);
   tree2->SetBranchAddress("VectorL", &VectorL, &b_VectorL);
   tree2->SetBranchAddress("VectorR", &VectorR, &b_VectorR);
   tree2->SetBranchAddress("VectorR_loop", &VectorR_loop, &b_VectorR_loop);
   tree2->SetBranchAddress("VectorL_loop", &VectorL_loop, &b_VectorL_loop);
